FILLER_WORDS = [
    "uh", "um", "umm", "uhh", "er", "ah", "hmm", "huh",
    "like", "you know", "i mean", "kind of", "sort of",
    "basically", "actually", "literally", "seriously",
    "right", "okay", "ok", "so", "well", "anyway",
    "anyways", "alright", "yeah", "yep", "nope",
    "just", "maybe", "probably", "perhaps",
    "i guess", "i think", "i believe", "i feel like",
    "to be honest", "honestly", "frankly",
    "in a way", "at the end of the day",
    "for the most part", "more or less",
    "you see", "you know what i mean",
    "if that makes sense", "does that make sense",
    "and stuff", "and things", "or something",
    "and all that", "that kind of thing",
    "stuff like that", "things like that",
    "so yeah", "so basically", "so actually",
    "so yeah guys", "so yeah", "so um",
    "uh so", "um so", "like i said",
    "as i said", "as i mentioned",
    "you guys", "guys", "folks",
    "let's see", "let me see", "let me think",
    "how do i put this", "how should i say this",
    "what i'm trying to say", "what i mean is",
    "the thing is", "the point is",
    "by the way", "on top of that",
    "at this point", "at this stage",
    "in this case", "in that case",
    "at the same time", "at the moment",
    "for example", "for instance",
    "in general", "generally speaking",
    "in other words", "that being said",
    "having said that", "with that said",
    "long story short", "short story",
    "believe it or not", "you know what",
    "guess what", "think about it",
    "if you will", "sorta", "kinda",
    "ya know", "uh huh", "mm hmm",
    "right right", "yeah yeah",
    "and yeah", "so right",
    "i suppose", "i assume",
    "to some extent", "to a certain extent",
    "as it were", "if you like",
    "as such", "more or less",
    "all in all", "overall",
    "technically", "theoretically",
    "pretty much", "almost",
    "basically speaking",
    "whatsoever", "whatever",
    "you could say", "let's say",
    "kind of like", "sort of like"
]
